# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 21:57
from __future__ import unicode_literals

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome', models.CharField(max_length=50)),
                ('ra', models.IntegerField(unique=True)),
                ('password', models.CharField(max_length=150)),
                ('perfil', models.CharField(default='C', max_length=1)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', core.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='ArquivosFoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'ArquivosFoto',
            },
        ),
        migrations.CreateModel(
            name='ArquivosQuestao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'ArquivosQuestao',
            },
        ),
        migrations.CreateModel(
            name='ArquivosResposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'ArquivosResposta',
            },
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, null=True)),
                ('ra', models.CharField(max_length=80, null=True)),
                ('email', models.CharField(max_length=80, null=True)),
                ('celular', models.CharField(max_length=11, null=True)),
                ('codigo_acesso', models.CharField(max_length=120, null=True)),
                ('confirmado', models.BooleanField(default=False)),
                ('matricula_aceita', models.BooleanField(default=False)),
                ('foto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='core.ArquivosFoto')),
            ],
            options={
                'db_table': 'Candidado',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=5)),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(blank=True, max_length=50)),
                ('carga_horaria', models.IntegerField(default=1000)),
                ('ativo', models.BooleanField(default=True)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'Curso',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=240)),
                ('carga_horaria', models.SmallIntegerField()),
                ('teoria', models.DecimalField(decimal_places=2, max_digits=3)),
                ('pratica', models.DecimalField(decimal_places=2, max_digits=3)),
                ('ementa', models.TextField()),
                ('competencias', models.TextField()),
                ('habilidades', models.TextField()),
                ('conteudo', models.TextField()),
                ('bibliografia_complementar', models.TextField()),
                ('bibliografia_basica', models.TextField()),
            ],
            options={
                'db_table': 'Disciplina',
            },
        ),
        migrations.CreateModel(
            name='DisciplinaOfertada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('semestre', models.CharField(max_length=1)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinasOfertadas', to='core.Disciplina')),
            ],
            options={
                'db_table': 'DisciplinaOfertada',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradeCurricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.SmallIntegerField()),
                ('semestre', models.CharField(max_length=1)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradesCurriculares', to='core.Curso')),
            ],
            options={
                'db_table': 'GradeCurricular',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.SmallIntegerField()),
                ('disciplinas', models.ManyToManyField(db_table='PeriodoDisicplina', related_name='periodos', to='core.Disciplina')),
                ('gradeCurricular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='core.GradeCurricular')),
            ],
            options={
                'db_table': 'Periodo',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra', models.IntegerField(unique=True)),
                ('apelido', models.CharField(max_length=30, null=True, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=80)),
                ('celular', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'Professor',
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(default='')),
                ('data_limite_entrega', models.DateField(default='AAAA-MM-DD')),
                ('numero', models.IntegerField()),
                ('data', models.DateField(default='')),
            ],
            options={
                'db_table': 'Questao',
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_avaliacao', models.DateField()),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4)),
                ('avaliacao', models.TextField()),
                ('descricao', models.TextField()),
                ('data_de_envio', models.DateField()),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='core.Questao')),
            ],
            options={
                'db_table': 'Resposta',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(max_length=15)),
                ('turma_sigla', models.CharField(max_length=1)),
                ('cursos', models.ManyToManyField(to='core.Curso')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Professor')),
            ],
            options={
                'db_table': 'Turma',
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email', models.EmailField(default='', max_length=254)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='core.Curso')),
                ('turmas', models.ManyToManyField(blank=True, db_table='Matricula', related_name='alunos', to='core.Turma')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.usuario',),
        ),
        migrations.AddField(
            model_name='questao',
            name='turma',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='core.Turma'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='turma',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='core.Turma'),
        ),
        migrations.AddField(
            model_name='arquivosresposta',
            name='resposta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivosResposta', to='core.Resposta'),
        ),
        migrations.AddField(
            model_name='arquivosquestao',
            name='questao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivosQuestao', to='core.Questao'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='core.Aluno'),
        ),
    ]
