# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_areaaluno_contato_disciplinas_esquecisenha_form_index_listacursos_login_noticia1_noticia2_noticias_n'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AreaAluno',
        ),
        migrations.DeleteModel(
            name='Contato',
        ),
        migrations.DeleteModel(
            name='Disciplinas',
        ),
        migrations.DeleteModel(
            name='esqueciSenha',
        ),
        migrations.DeleteModel(
            name='form',
        ),
        migrations.DeleteModel(
            name='index',
        ),
        migrations.DeleteModel(
            name='ListaCursos',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='noticia1',
        ),
        migrations.DeleteModel(
            name='noticia2',
        ),
        migrations.DeleteModel(
            name='Noticias',
        ),
        migrations.DeleteModel(
            name='novaDisciplina',
        ),
        migrations.DeleteModel(
            name='novoUsuario',
        ),
        migrations.DeleteModel(
            name='SobreCurso',
        ),
    ]
