# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_disciplina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra', models.IntegerField(unique=True)),
                ('apelido', models.CharField(max_length=30, null=True, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=80)),
                ('celular', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'Professor',
            },
        ),
    ]
