# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(max_length=15)),
                ('turma_sigla', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'Turma',
            },
        ),
        migrations.AlterModelTable(
            name='curso',
            table='Curso',
        ),
        migrations.AddField(
            model_name='turma',
            name='cursos',
            field=models.ManyToManyField(to='core.Curso'),
        ),
        migrations.AddField(
            model_name='turma',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Professor'),
        ),
    ]
