# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20171121_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='turmas',
            field=models.ManyToManyField(blank=True, db_table='Matricula', related_name='alunos', to='core.Turma'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='core.Curso'),
        ),
    ]
