# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_gradecurricular_periodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivosFoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'ArquivosFoto',
            },
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, null=True)),
                ('ra', models.CharField(max_length=80, null=True)),
                ('email', models.CharField(max_length=80, null=True)),
                ('celular', models.CharField(max_length=11, null=True)),
                ('codigo_acesso', models.CharField(max_length=120, null=True)),
                ('confirmado', models.BooleanField(default=False)),
                ('matricula_aceita', models.BooleanField(default=False)),
                ('foto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='core.ArquivosFoto')),
                ('turma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='core.Turma')),
            ],
            options={
                'db_table': 'Candidado',
            },
        ),
    ]
