# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_arquivosfoto_candidato'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivosQuestao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'ArquivosQuestao',
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data_limite_entrega', models.DateField()),
                ('numero', models.IntegerField()),
                ('data', models.DateField()),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='core.Turma')),
            ],
            options={
                'db_table': 'Questao',
            },
        ),
        migrations.AddField(
            model_name='arquivosquestao',
            name='questao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivosQuestao', to='core.Questao'),
        ),
    ]
